### ISSUE TITLE
Record Player doesn't play any music after importing from file.

### ISSUE THREAD

**Issue by Ristellise** [asiekierka/CharsetMC#208]
Log file: [Here](https://paste.ee/p/uXpq3)

When the disk is played, the log is spammed with:
```
[17:31:52] [Thread-8/ERROR]: Error in class 'SourceLWJGL OpenAL'
[17:31:52] [Thread-8/ERROR]: Invalid name parameter.
```

**Comment by ofseaandstars** [comment]
I seem to be having the same issue with the record player not playing anything. Although my error log is different:

I get this error when using a .ogg file (which is supported by default):
```
Exception in thread "Thread-148" [11:10:26] [Thread-148/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: Could not initialize class pl.asie.charset.module.audio.storage.AudioResampler
[11:10:26] [Thread-148/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at pl.asie.charset.module.audio.storage.AudioRecordThread.run(AudioRecordThread.java:165)
[11:10:26] [Thread-148/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Thread.run(Unknown Source)
```

And this error when using a .mp3 file (using the 'NotEnoughCodecs' mod).

```
Exception in thread "Thread-88" [11:09:17] [Thread-88/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: com/laszlosystems/libresample4j/Resampler
[11:09:17] [Thread-88/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at pl.asie.charset.module.audio.storage.AudioResampler.<clinit>(AudioResampler.java:27)
[11:09:17] [Thread-88/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at pl.asie.charset.module.audio.storage.AudioRecordThread.run(AudioRecordThread.java:165)
[11:09:17] [Thread-88/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Thread.run(Unknown Source)
[11:09:17] [Thread-88/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.ClassNotFoundException: com.laszlosystems.libresample4j.Resampler
[11:09:17] [Thread-88/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[11:09:17] [Thread-88/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[11:09:17] [Thread-88/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[11:09:17] [Thread-88/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 3 more
[11:09:17] [Thread-88/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException
```

This affected both single-player and multi-player.

**Forge:** 14.23.2.2640
**CharsetLib:** 0.5.0.208
**Charset Audio:** 0.5.0.208

**Comment by asiekierka** [comment]
Ugh, sorry. Fixed in 0.5.0.210.

https://github.com/CharsetMC/Charset/commit/049d6a54dde78488baf3093dfcf612d766c31a58

**Comment by Ristellise** [comment]
@asiekierka Still not fixed. Tried with Charset Ver 212 and still got the same error.

**Comment by asiekierka** [comment]
@Ristelle Since you're using the CI builds and not the Curse builds,... which JAR? Logs?

**Comment by asiekierka** [comment]
Oh, oh. Sorry. I fixed bug #2 (@AshenGaming ) and not yours. I'll check yours.

**Comment by asiekierka** [comment]
>AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005

I would worry about this. Seems like a Windows audio issue?

Are you sure other audio is working in-game?

**Comment by Ristellise** [comment]
[Here's a video on it.](https://streamable.com/7k3ue)

**Comment by Ristellise** [comment]
[fml-client-latest.log](https://github.com/CharsetMC/Charset/files/1867652/fml-client-latest.log)
[latest.log](https://github.com/CharsetMC/Charset/files/1867653/latest.log)
More logs.  
Version: Charset-0.5.0.212-full

**Comment by asiekierka** [comment]
Try the non-full version. Just out of curiosity.
