### ISSUE TITLE
Textures all go to hell in & when using a resourcepack

### ISSUE THREAD

**Issue by b0bst3r** [asiekierka/CharsetMC#60]
So normal looking latch - http://i.imgur.com/KMbSsdY.png
And when a resourcepack is used  - http://i.imgur.com/rFZLBNV.png
And it's not just the latch but all of them  - http://i.imgur.com/G9KuggL.png

Also when removing the resourcepack things go even whackier and most items in & lose all textures completely and you have to quit MC and reload to get them back.

**Comment by asiekierka** [comment]
If we're talking about 1.9, this is fixed already and will be in the next release. If we're talking about 1.8.9, !?!?

**Comment by b0bst3r** [comment]
Yes sorry was 1.9 and good to know

**Comment by b0bst3r** [comment]
Not sure which "next release" you meant but this is still happening in 0.3.0-pre3 (MC 1.9)
